apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sample-local-storage
